apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-jogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-jogos
  template:
    metadata:
      labels:
        app: fcg-jogos
    spec:
      containers:
      - name: fcg-jogos
        image: fabriciorosanet/fcg-jogos-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: RabbitMQ__HostName
          value: "rabbitmq" # <--- AJUSTE AQUI
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__UserName
          value: "guest"
        - name: RabbitMQ__Password
          value: "guest"
        livenessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5