{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fcg-jogos-api.fullname" . }}-secret
  labels:
    app: {{ include "fcg-jogos-api.name" . }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
